kind: Deployment
apiVersion: apps/v1
metadata: 
  name: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
      - name: keycloak
        image: quay.io/keycloak/keycloak:21.1.1
        args: ["start-dev"]
        env:
        - name: KEYCLOAK_ADMIN                                                                                            
          value: "admin"                                                                                                 
        - name: KEYCLOAK_ADMIN_PASSWORD                                                                                   
          value: "admin"                                                                                                  
        - name: KC_PROXY                                                                                                  
          value: "edge"                                                                                                  
        ports:
        - name: http
          containerPort: 8080
        readinessProbe:
          httpGet:
            path: /realms/master
            port: 8080         

---      

apiVersion: v1
kind: Service
metadata:
  name: keycloak
  labels:
    app: keycloak
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:us-west-2:467575538618:certificate/e1373cd6-9ff7-4dc1-a423-fe959d01554c
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
spec:
  ports:
  - port: 443
    targetPort: 8080
    protocol: TCP
  selector:
    app: keycloak
  type: LoadBalancer 

